### ISSUE TITLE
Cannot compile using boost 1.61.0 

### ISSUE THREAD

**Issue by akomaty** [idiap/IBDiarization#3]
```
Scanning dependencies of target diarizeme
[  6%] Building CXX object CMakeFiles/diarizeme.dir/idiap/user/akomaty/ODESSA/codes/IBDiarization/src/diarization/src/diarizeme.cpp.o
In file included from /idiap/user/akomaty/ODESSA/codes/IBDiarization/src/diarization/cmake/../../aibfeat/include/gmm.h:23:0,
                 from /idiap/user/akomaty/ODESSA/codes/IBDiarization/src/diarization/cmake/../../aibfeat/include/hmmreadwrite.h:23,
                 from /idiap/user/akomaty/ODESSA/codes/IBDiarization/src/diarization/src/diarizeme.cpp:39:
/idiap/user/akomaty/ODESSA/codes/IBDiarization/src/diarization/cmake/../../utils/include/global.h:39:11: error: expected identifier before numeric constant
 #define P 2 //variable to decide the initialization
           ^
/idiap/user/akomaty/ODESSA/codes/IBDiarization/src/diarization/cmake/../../utils/include/global.h:39:11: error: expected ‘>’ before numeric constant
In file included from /remote/idiap.svm/group.torch5spro/conda/envs/bob-devel-py27/include/boost/smart_ptr/make_shared_array.hpp:12:0,
                 from /remote/idiap.svm/group.torch5spro/conda/envs/bob-devel-py27/include/boost/smart_ptr/make_shared.hpp:18,
                 from /remote/idiap.svm/group.torch5spro/conda/envs/bob-devel-py27/include/boost/make_shared.hpp:15,
                 from /remote/idiap.svm/group.torch5spro/conda/envs/bob-devel-py27/include/boost/smart_ptr.hpp:28,
                 from /idiap/user/akomaty/ODESSA/codes/IBDiarization/src/diarization/cmake/../../utils/include/tools.h:38,
                 from /idiap/user/akomaty/ODESSA/codes/IBDiarization/src/diarization/cmake/../../aIB/include/aIB.h:34,
                 from /idiap/user/akomaty/ODESSA/codes/IBDiarization/src/diarization/src/diarizeme.cpp:45:
/remote/idiap.svm/group.torch5spro/conda/envs/bob-devel-py27/include/boost/smart_ptr/detail/array_count_impl.hpp:18:59: error: ‘A’ was not declared in this scope
         class sp_counted_impl_pda<P, ms_in_allocator_tag, A>
                                                           ^
/remote/idiap.svm/group.torch5spro/conda/envs/bob-devel-py27/include/boost/smart_ptr/detail/array_count_impl.hpp:18:60: error: type/value mismatch at argument 1 in template parameter list for ‘template<class P, class D, class A> class boost::detail::sp_counted_impl_pda’
         class sp_counted_impl_pda<P, ms_in_allocator_tag, A>
                                                            ^
/remote/idiap.svm/group.torch5spro/conda/envs/bob-devel-py27/include/boost/smart_ptr/detail/array_count_impl.hpp:18:60: error:   expected a type, got ‘2’
/remote/idiap.svm/group.torch5spro/conda/envs/bob-devel-py27/include/boost/smart_ptr/detail/array_count_impl.hpp:18:60: error: template argument 3 is invalid
CMakeFiles/diarizeme.dir/build.make:62: recipe for target 'CMakeFiles/diarizeme.dir/idiap/user/akomaty/ODESSA/codes/IBDiarization/src/diarization/src/diarizeme.cpp.o' failed
make[2]: *** [CMakeFiles/diarizeme.dir/idiap/user/akomaty/ODESSA/codes/IBDiarization/src/diarization/src/diarizeme.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/diarizeme.dir/all' failed
make[1]: *** [CMakeFiles/diarizeme.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by mrsrikanth** [comment]
Hi Alain,

Could you please confirm that you are running the latest version?
This seemed to have been fixed in the version updated 1-2 weeks ago.

Thanks,
Srikanth

**Comment by akomaty** [comment]
Thank you Srikanth, problem solved after updating my git repository!
